version: '3.8'

services:
  cashier-app:
    image: php:8.1-cli
    container_name: aseng-cashier
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:9000
